// The list of games shown on the dashboard.
// To add a game: put it in games/<folder>/ and add an entry here.
window.GAMES = [
  {
    id: "flappy-bird",
    title: "Flappy Bird",
    description: "Tap to flap and fly through the pipes.",
    url: "games/flappy-bird/index.html",
    icon: "🐤",
    color: "#4ec0ca",
    bestScoreKey: "flappy-bird:best",
  },
  {
    id: "snake",
    title: "Snake",
    description: "Eat, grow, and avoid the walls.",
    url: "games/snake/index.html",
    icon: "🐍",
    color: "#3bb184",
    bestScoreKey: "snake:best",
  },
  {
    id: "memory-match",
    title: "Memory Match",
    description: "Find all eight matching pairs.",
    url: "games/memory-match/index.html",
    icon: "🧠",
    color: "#8c75bf",
  },
  {
    id: "tic-tac-toe",
    title: "Tic-Tac-Toe",
    description: "Take on the computer in a classic.",
    url: "games/tic-tac-toe/index.html",
    icon: "⭕",
    color: "#e77d56",
  },
  {
    id: "2048",
    title: "2048",
    description: "Slide and combine tiles to reach 2048.",
    url: "games/2048/index.html",
    icon: "🔢",
    color: "#d6a74a",
    bestScoreKey: "2048:best",
  },
  {
    id: "breakout",
    title: "Breakout",
    description: "Bounce the ball and clear every brick.",
    url: "games/breakout/index.html",
    icon: "🧱",
    color: "#db6657",
  },
  {
    id: "minesweeper",
    title: "Minesweeper",
    description: "Read the clues and clear the minefield.",
    url: "games/minesweeper/index.html",
    icon: "💣",
    color: "#607d8b",
  },
  {
    id: "pong",
    title: "Pong",
    description: "Challenge the computer to a rally.",
    url: "games/pong/index.html",
    icon: "🏓",
    color: "#36a6a0",
  },
  {
    id: "whack-a-mole",
    title: "Whack-a-Mole",
    description: "Catch as many moles as you can in 30 seconds.",
    url: "games/whack-a-mole/index.html",
    icon: "🐹",
    color: "#b8754d",
  },
];
